config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "welcome#index"
  resources :categories
  resources :products  
  resources :carts
  resources :sales
  post 'products/:id/buy', to: 'products#buy', as: 'buy_product'
  get 'carts/current_order', to: 'carts#current_order', as: 'current_order'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  

  #get 'admin', to: 'admin#index' 
end

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3 text-bg-dark" style="position: fixed; bottom: 0;">
  <div class="container-md">
    <p class="text-center m-0">Файна плитка тут: <a href="/" class='text-warning'> Betonna lavka</a> і тут: 
    <a href="/products" class='text-warning'> Products</a>.</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="p-3 text-bg-warning flex-shrink-0">
    <div class="container-md">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/" class="nav-link px-2 text-dark">Betonna lavka</a></li>
          <li><a href="/products" class="nav-link px-2 text-dark">Products</a></li>
          <li><a href="#" class="nav-link px-2 text-dark">Gallery</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control form-control-dark " placeholder="Search..." aria-label="Search">
        </form>
 
 <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://cdn-icons-png.flaticon.com/512/126/126083.png" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li>
                <%= link_to 'Cart', carts_url, class:"dropdown-item"  %>
            </li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Sign out</a></li>
          </ul>
        </div>

      <%- if user_signed_in? %>
        <%= button_to "My Orders", carts_path, method: :get %>
        <a>
        <img src="https://cdn-icons-png.flaticon.com/512/126/126083.png" alt="mdo" width="32" height="32" >
        </a>
         <div class="col-md-3 text-end">
        <%= button_to 'Logout' , destroy_user_session_path, method: :delete, form: {turbolink: false},  class:'btn btn-primary'%>
        </div>
      <% else%>
      <div class="col-md-3 text-end">
        <%= link_to new_user_session_path do %>
        <button type="button" class='btn btn-outline-primary me-2'>Login</button>
        <% end%>
        <%= link_to new_user_registration_path do %>
        <button type="button" class="btn btn-warning">Sign-up</button>
        <% end%>
      </div>
      <% end %>
    </div>
  </div>
</header>
        