config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "welcome#index"
  resources :categories
  resources :products  
  resources :carts
  resources :sales
  post 'products/:id/buy', to: 'products#buy', as: 'buy_product'
  get 'carts/current_order', to: 'carts#current_order', as: 'current_order'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  

  #get 'admin', to: 'admin#index' 
end

app/models/cart.rb
class Cart < ApplicationRecord
    attribute :quantity, :integer, default: 1
    attribute :order_session, :integer, default: 1 

    
    has_many :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  def update
  
    @cart.quantity = params[:cart][:quantity]
    @cart.subtotal = @cart.quantity * @cart.products_price
  
    if @cart.save
      redirect_to carts_path, notice: 'Cart was successfully updated.'
    else
      render :edit
    end
  end
  
  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
 # def create
    # @cart = Cart.new(cart_params)

   #respond_to do |format|
      #if @cart.save
       #format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        #format.json { render :show, status: :created, location: @cart }
      #else
        #format.html { render :new, status: :unprocessable_entity }
        #format.json { render json: @cart.errors, status: :unprocessable_entity }
      #end
    #end
 # end

  # PATCH/PUT /carts/1 or /carts/1.json
  #def update
    #respond_to do |format|
      #if @cart.update(cart_params)
        #format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        #format.json { render :show, status: :ok, location: @cart }
      #else
        #format.html { render :edit, status: :unprocessable_entity }
        #format.json { render json: @cart.errors, status: :unprocessable_entity }
      #end
    #end
 # end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def create
    @cart = Cart.new(cart_params)
    @cart.user = current_user
    if @cart.save
      Sale.create_from_cart_items(current_user, current_user.carts)
      Cart.destroy_all
      redirect_to root_path
    else
      render :new
    end
  end
  

  def current_order
    #@carts = Cart.where(user_id: current_user.id).group(:order_session).select('*, MAX(id) as id')
  end

  def submit_button
    Cart.select(:curent_order_sission.max, user_id: current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit(:user_id, :product_product, :quantity, :subtotal)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
  <p>
    <strong>User:</strong>
    <%= cart.user_id %>
  </p>

  <p>
    <strong>Product product:</strong>
    <%= cart.products_product %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= cart.quantity %>
  </p>
  <p>
    <strong>Subtotal:</strong>
    <%= cart.subtotal %>
  </p>
</div>

app/views/carts/_current_order.html.erb
<table>
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Subtotal</th>
    </tr>
  </thead>
  <tbody>
    <% @carts.select{|cart| cart.user_id == current_user.id}each do |item| %>
      <tr>
        <td><%= item.products_product %></td>
        <td><%= item.products_price %></td>
        <td><%= item.quantity %></td>
        <td><%= item.subtotal %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :product_product, style: "display: block" %>
    <%= form.text_field :product_product %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.text_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/current_order.html.erb
<table>
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Subtotal</th>
    </tr>
  </thead>
  <tbody>
    <% @carts.select{|cart| cart.user_id == current_user.id}each do |item| %>
      <tr>
        <td><%= item.products_product %></td>
        <td><%= item.products_price %></td>
        <td><%= item.quantity %></td>
        <td><%= item.subtotal %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<table>
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Subtotal</th>
    </tr>
  </thead>
  <tbody>
    <% @carts.select { |cart| cart.user_id == current_user.id}.each do |item| %>
      <tr>
        <td><%= item.products_product %></td>
        <td><%= item.products_price %></td>
        <td><%= form_for(item, url: cart_path(item)) do |f| %>
          <%= f.number_field :quantity, min: 1, value: item.quantity, onchange: 'this.form.submit();' %>
        <% end %></td>
        <td><%= item.subtotal %></td>
        <td>
          <%= link_to "Remove", item, method: :delete %>
        </td>
      </tr>
    <% end %>
        <tr>
      <td colspan="3"></td>
      <td>Total:</td>
      <td><%= @carts.select{|cart| cart.user_id == current_user.id}.sum(&:subtotal) %></td>
    </tr>
  </tbody>
</table>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cart %>

<div>
  <%= link_to "Edit this cart", edit_cart_path(@cart) %> |
  <%= link_to "Back to carts", carts_path %>

  <%= button_to "Destroy this cart", @cart, method: :delete %>
</div>