config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "welcome#index"
  resources :categories
  resources :products  
  resources :carts
  resources :sales
  post 'products/:id/buy', to: 'products#buy', as: 'buy_product'
  get 'carts/current_order', to: 'carts#current_order', as: 'current_order'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  

  #get 'admin', to: 'admin#index' 
end

app/models/product.rb
class Product < ApplicationRecord
    validates :price, numericality: {greater_than: 0}
   

    has_one_attached :pics
    #belongs_to :category


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy buy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def buy
    @product = Product.find(params[:id])
    #Rails.logger.info("PARAMS: #{params.inspect}")
    @quantity = params[:quantity].to_i || 1
    @subtotal = @quantity * @product.price 
    @cart = Cart.new(product_id:  params[:id], quantity: params[:quantity], products_product: @product.product, user_id: current_user.id, subtotal: @subtotal )
  
    if @cart.save
      flash[:success] = 'Product added to cart'
    else
      flash[:error] = 'Could not add product to cart'
    end
    redirect_to @product
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:categorie, :product, :price, :weight, :pics)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
    def formatted_date(date)
        date.strftime('%d-%m-%Y')
        end
    def format_message
    end
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :categorie %>
    <%= form.select :category_id, Category.all.map{ |c| [c.name, c.id] }, { prompt: "Select a category" } %>
  </div>

  <div>
    <%= form.label :product, style: "display: block" %>
    <%= form.text_field :product %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.text_field :weight %>
  </div>

  <div>
    <%= form.label :pics, style: "display: block" %>
    <%= form.file_field :pics %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
<div class="card mb-3" id="<%= dom_id product %>">
  <% if product.pics.present? %>
    <%= image_tag product.pics, class: "card-img-top" %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= product.product %></h5>
    <p class="card-text"><strong>Category:</strong> <%= product.categorie %></p>
    <p class="card-text"><strong>Price:</strong> <%= number_to_currency(product.price) %></p>
    <p class="card-text"><strong>Weight:</strong> <%= product.weight %></p>
    <%= form_tag(buy_product_path(product), method: :post) do %>
      <%= label_tag(:quantity, "Quantity:") %>
      <%= number_field_tag(:quantity, 1, min: 1, max: 100, class: "form-control mb-3") %>
      <%= submit_tag 'Buy it', class: 'btn btn-primary product_submit_button'  %>
    <% end %>
  </div>
</div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>
  
<div id="products" class="d-flex justify-content-around row">
  <% @products.each do |product| %>
   <div class="col-sm-6 col-md-4 col-lg-3 mb-4" >
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  
    </div>
  <% end %>
</div>  
</div>

  <%if current_user.present? && current_user.email == "sviatoslavpintsak@gmail.com"%>
    <%= link_to "New product", new_product_path %>
  <%end%>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
  
  <%= link_to "New product", new_product_path %>

</div>

app/views/products/test.html.erb
<h1>Products</h1>

<div id="products" class="d-flex justify-content-center">
  <% @products.each do |product| %>
   <div >
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
    </div>
  <% end %>
</div>